### PR TITLE
chore: cleanup repo

### PR DESCRIPTION
**Pull request by Stormix**

### CODE REVIEW

**Comment by yezz123** [comment]
hsbou hsbou

**Comment by yezz123** [comment]
ou bach katmchi sfina bsalat 3la nbina

**Comment by yezz123** [comment]
bach katmchi ou trssi bsalat 3la l9orchi

**Comment by 0x00Jeff** [comment]
What the hell happened here xd

**Review by AlaaZorkane — APPROVED** [review]

**Comment by AlaaZorkane** [comment]
LGTM!

**Comment by 0UR4N05** [comment]
pepepopooo

**Comment by 0x00Jeff** [comment]
Ayyyyyyyyyyyy ouranos

**Comment by yezz123** [comment]
@0x00Jeff rj3 asat we miss u

**Comment by 0UR4N05** [comment]
jeff rj3 rah an3dk mn swtk (wal3iyado bilah)

**Comment by 0x00Jeff** [comment]
How does one bite sound ?

**Comment by 0UR4N05** [comment]
u really don't wanna know so joine asat

**Pull request closed without merging**
